# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1da79fa0d2cdd81922fe1d581271f34bfc61a19bd3741a52bf502087d7dc8c8813e63f2b6cd2f4edb76281dea01f47fc13c8cfffb41b6fba837fe6a357c6ff3

test:
  secret_key_base: bcdda8c0766c2f23b401f4ddd413a317b877d4a7684e5797808ff13374cbec75d4be3b82b25e2e2336db4dddf9b46e9785c75c314004b142e5083a240c04b569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
